### PR TITLE
Explicitly instruct Nginx not to buffer responses.

### PR DESCRIPTION
**Pull request by qubyte**
@BrandwatchLtd/vizia Ready for review.

### CODE REVIEW

**Comment by chrisnewtn** [comment]
:+1:

**Comment by allouis** [comment]
:+1: LGTM

**Comment by allouis** [comment]
will wait for @cham

**Comment by cham** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Pull request merged**
